import './globals.css'
import { Roboto_Flex } from 'next/font/google'

const roboto = Roboto_Flex({ 
  subsets: ['latin']
 })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body className={roboto.className}>{children}</body>
    </html>
  )
}
